<?php
/**
 * Created by PhpStorm.
 * User: TheresaPatricia
 * Date: 5/08/16
 * Time: 12:11 PM
 */

class StaffPage extends Page {
    private static $description = "A Staff Member";

    private static $can_be_root = false;

    private static $db = array(
        'Phone' => 'Varchar(11)',
        'Email' => 'Varchar(255)'
    );

    private static $has_one = array(
        'Photo' => 'Image',
        'Department' => 'Department',
        'Role' => 'Role'
    );

    public function getCMSFields()
    {
        $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

        $fields->addFieldsToTab(
            'Root.Main',
            PhoneNumberField::create('Phone'),
            'Content'
        );

        $fields->addFieldsToTab(
            'Root.Main',
            EmailField::create('Email'),
            'Content'
        );

        $fields->addFieldsToTab(
            'Root.Main',
            UploadField::create('Photo'),
            'Content'
        );

        $fields->addFieldsToTab(
            'Root.Main',
            DropdownField::create(
                'RoleID',
                'Role',
                Role::get()->map('ID', 'Title')
            )->setEmptyString('(Select)'),
            'Content'
        );

        $fields->addFieldsToTab(
            'Root.Main',
            DropdownField::create(
                'DepartmentID',
                'Department',
                Department::get()->map('ID', 'Title')
            )->setEmptyString('(Select)'),
            'Content'
        );

        return $fields;
    }
}

class StaffPage_Controller extends Page_Controller {

}